# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallybook" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "ffa174981ddd46c04b64a6eda21231a243db163b783099293b0735d85a2732d7"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "92ae76edb57a22aa7acdad76966f100f33d4e28553061f9dccafcfac8ece6d7f"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "594545de47447c31463913cd755eb2dcf13d077d4440ab8a87707b61b4888d11"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f62f51e349601d163c93d8e2217297ac3c3db5d64c5944d0f7e60d7860ed2eb"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tallybook"
  desc "A local ledger for what your coding agents cost, and what you could have paid instead"
  homepage "https://github.com/magna-nz/tallybook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallybook"
  binary "tallybook-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook-mcp"]
    end
  end

  # No zap stanza required
end
