# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallybook" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "947c962f9c091c9173a454e73261475a91eeaccf09181c0d98ee873f27c49a9d"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e65679b2a7e96aef299249acd507de3a221ffe5948c13fbb2cfba0ea4fd73348"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6c31cb17ec2b41bed79f13bf99b4f34d64177456084cc0e837a43dcb0b90703c"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a8f4ebe1a2dffb55b0298f7173b2c74070eafb2e0e4fc251e4e6b58a2ecbef6c"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tallybook"
  desc "A local ledger for what your coding agents cost, and what you could have paid instead"
  homepage "https://github.com/magna-nz/tallybook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallybook"
  binary "tallybook-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook-mcp"]
    end
  end

  # No zap stanza required
end
