# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallybook" do
  version "1.2.0"

  on_macos do
    on_arm do
      sha256 "76c76a3b75614b3989b2970e977fec203117741a5195e9d445e84a3804c2a963"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "681d01be29097167d196b919d0337208f02c709a7b0339c97462c4d87d1c3b46"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2c1aeb8e7d917dc73fd6be65c9aaab33f0100a134f2c3624b34ff1ee47a9f797"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd1d34b4da2187bdc960b1234fb0644107cfbf528b6dd4bf6bff238cb4dee804"
      url "https://github.com/magna-nz/tallybook/releases/download/v#{version}/tallybook_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tallybook"
  desc "A local ledger for what your coding agents cost, and what you could have paid instead"
  homepage "https://github.com/magna-nz/tallybook"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallybook"
  binary "tallybook-mcp"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallybook-mcp"]
    end
  end

  # No zap stanza required
end
